# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2324df07ebf18563939d1e2a40bd5cdd"
application_url = "https://times-younger-assignment-dinner.trycloudflare.com"
embedded = true
name = "custom-checkout-field"
handle = "custom-checkout-field-10"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://times-younger-assignment-dinner.trycloudflare.com/auth/callback",
  "https://times-younger-assignment-dinner.trycloudflare.com/auth/shopify/callback",
  "https://times-younger-assignment-dinner.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
include_config_on_deploy = true
dev_store_url = "apps-test124.myshopify.com"
automatically_update_urls_on_dev = true
